name: build

on:
  pull_request:

jobs:
  build_wheel:
    name: build_wheel
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build libenvoy_mobile.so
        run: |
          : \
          && cd envoy-mobile \
          && ./bazelw build //:libenvoy_mobile.so \
          && mv bazel-bin/libenvoy_mobile.so ../ \
          && cd ../ \
          && :
      - uses: actions/cache@v2
        with:
          path: libenvoy_mobile.so
          key: ${{ runner.os }}-${{ hashFiles('./envoy-mobile/**') }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions-rs/toolchain@v1
      - name: Install maturin
        run: pip install maturin==0.12.1
      - name: Build wheel
        run: maturin build
